### ISSUE TITLE
cannot do `bundle install binstubs` on SmartOS

### ISSUE THREAD

**Issue by bixu** [chef/omnibus-chef#250]
```
[admin@c9308a86-1b42-4a68-f463-d67bfdb483d8 ~/omnibus-chef]$ cat /etc/release 
                                SmartOS x86_64
              Copyright 2010 Sun Microsystems, Inc.  All Rights Reserved.
              Copyright 2010-2013 Joyent, Inc.  All Rights Reserved.
                        Use is subject to license terms.
                   See joyent_20140613T024634Z for assembly date and time.

[admin@c9308a86-1b42-4a68-f463-d67bfdb483d8 ~/omnibus-chef]$ cat /etc/product 
Name: Joyent Instance
Image: base64 14.2.0
Documentation: http://wiki.joyent.com/jpc2/SmartMachine+Base

[admin@c9308a86-1b42-4a68-f463-d67bfdb483d8 ~/omnibus-chef]$ bundle install --binstubs
Fetching gem metadata from https://rubygems.org/.......
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using addressable 2.3.6
Using cabin 0.6.1
Using arr-pm 0.0.9
Using backports 3.6.1
Installing multipart-post 2.0.0
Installing faraday 0.9.0
Installing berkshelf-api-client 1.2.0
Installing buff-extensions 1.0.0
Installing hashie 2.1.2
Installing varia_model 0.4.0
Installing buff-config 1.0.1
Installing buff-ruby_engine 0.1.0
Installing buff-shell_out 0.2.0
Installing hitimes 1.2.2
Installing timers 4.0.1
Installing celluloid 0.16.0
Installing nio4r 1.0.1
Installing celluloid-io 0.16.0
Installing minitar 0.5.4
Installing sawyer 0.5.5
Installing octokit 3.3.1
Installing retryable 1.3.6
Installing buff-ignore 1.1.1
Installing erubis 2.7.0
Using json 1.8.1
Using mixlib-log 1.6.0
Installing mixlib-authentication 1.3.0
Installing net-http-persistent 2.9.4
Installing semverse 1.2.1
Installing ridley 4.0.0

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/local/bin/ruby212 extconf.rb 
-> sh /tmp/bundler20140926-79999-18c0h7/dep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure --prefix=/tmp/bundler20140926-79999-18c0h7/dep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disable-doc-docset --disable-qt --disable-examples --disable-flatzinc
checking for the host operating system... configure: error: Host OS not supported.
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
        from extconf.rb:97:in `chdir'
        from extconf.rb:97:in `run'
        from extconf.rb:104:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20140926-79999-18c0h7/dep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2 for inspection.
Results logged to /tmp/bundler20140926-79999-18c0h7/dep-selector-libgecode-1.0.2/extensions/x86_64-solaris2.11/2.1.2/dep-selector-libgecode-1.0.2/gem_make.out
An error occurred while installing dep-selector-libgecode (1.0.2), and Bundler cannot continue.
Make sure that `gem install dep-selector-libgecode -v '1.0.2'` succeeds before bundling.
```

**Comment by bahamas10** [comment]
@lamont-granquist i bet your issue can be solved by lying to the configure script and saying you are running Linux https://github.com/chef/dep-selector-libgecode/pull/41
