### ISSUE TITLE
omnibus build failed on download ruby 2.2.2

### ISSUE THREAD

**Issue by ranjib** [chef/omnibus-chef#434]
Stack trace:

```sh
               
omnibus@ubuntu:~/omnibus-chef$ bundle exec omnibus build chef -l debug
                              [CLI] I | Using config from 'omnibus.rb'
DL is deprecated, please use Fiddle
Building chef ...
            [Software: preparation] I | Resolving manifest entry for preparation
         [NullFetcher: preparation] I | Fetching `preparation' (nothing to fetch)
                   [Software: zlib] I | Resolving manifest entry for zlib
                [Software: libedit] I | Resolving manifest entry for libedit
                [Software: ncurses] I | Resolving manifest entry for ncurses
                [Software: cacerts] I | Resolving manifest entry for cacerts
                [Software: openssl] I | Resolving manifest entry for openssl
                 [Software: xproto] I | Resolving manifest entry for xproto
            [Software: util-macros] I | Resolving manifest entry for util-macros
               [Software: libiconv] I | Resolving manifest entry for libiconv
             [Software: makedepend] I | Resolving manifest entry for makedepend
             [Software: pkg-config] I | Resolving manifest entry for pkg-config
                [Software: libyaml] I | Resolving manifest entry for libyaml
                [Software: libtool] I | Resolving manifest entry for libtool
                 [Software: libffi] I | Resolving manifest entry for libffi
                   [Software: gdbm] I | Resolving manifest entry for gdbm
                   [Software: ruby] I | Resolving manifest entry for ruby
               [Software: rubygems] I | Resolving manifest entry for rubygems
                [Software: bundler] I | Resolving manifest entry for bundler
             [NullFetcher: bundler] I | Fetching `bundler' (nothing to fetch)
                   [Software: ohai] I | Resolving manifest entry for ohai
             [Software: appbundler] I | Resolving manifest entry for appbundler
          [NullFetcher: appbundler] I | Fetching `appbundler' (nothing to fetch)
                   [Software: chef] I | Resolving manifest entry for chef
        [Software: shebang-cleanup] I | Resolving manifest entry for shebang-cleanup
     [NullFetcher: shebang-cleanup] I | Fetching `shebang-cleanup' (nothing to fetch)
       [Software: version-manifest] I | Resolving manifest entry for version-manifest
  [Software: openssl-customization] I | Resolving manifest entry for openssl-customization
[PathFetcher: openssl-customization] I | Digesting /var/cache/omnibus/src/openssl-customization with sha256
    [NullFetcher: version-manifest] I | Fetching `version-manifest' (nothing to fetch)
[PathFetcher: openssl-customization] I | Digesting /home/omnibus/omnibus-chef/files/openssl-customization with sha256
                 [GitFetcher: ohai] I | Fetching from `git://github.com/opscode/ohai'
                 [GitFetcher: chef] I | Fetching from `git://github.com/chef/chef'
                 [NetFetcher: ruby] I | Downloading from `http://opscode-omnibus-cache.s3.amazonaws.com/ruby-2.2.2-326e99ddc75381c7b50c85f7089f3260'
                 [NetFetcher: ruby] D | Retrying failed download (3)...                                                                                     0% (0 KB/sec)
                 [NetFetcher: ruby] D | Retrying failed download (2)...                                                                                     0% (0 KB/sec)
                 [NetFetcher: ruby] D | Retrying failed download (1)...                                                                                     0% (0 KB/sec)
                 [NetFetcher: ruby] E | Download failed - OpenURI::HTTPError!                                                                               0% (0 KB/sec)
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:353:in `open_http': 403 Forbidden (OpenURI::HTTPError)
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:704:in `open'
	from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:34:in `open'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/fetchers/net_fetcher.rb:184:in `download'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/fetchers/net_fetcher.rb:82:in `fetch'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/software.rb:633:in `fetch'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/project.rb:996:in `block (3 levels) in download'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/thread_pool.rb:64:in `call'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/thread_pool.rb:62:in `loop'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/thread_pool.rb:61:in `catch'
	from /home/omnibus/omnibus-chef/.bundle/ruby/2.1.0/bundler/gems/omnibus-01f64177c9cb/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
omnibus@ubuntu:~/omnibus-chef$ 

```

**Comment by ranjib** [comment]
@lamont-granquist ^

**Comment by lamont-granquist** [comment]
I uploaded it with --acl-public:

from my zsh history:

```
% s3cmd --acl-public -c ~/env/preprod/.s3cfg put ~/Downloads/ruby-2.2.2.tar.gz s3://opscode-omnibus-cache/ruby-2.2.2-cd03b28fd0b555970f5c4fd481700852
```

and it certainly worked for me locally without setting up any creds.

**Comment by ranjib** [comment]
gremlins.. :-/ , any idea  what log i should check? i cross checked with the previous commit, i can build omnibus installer from  8d0d923a3, and i can reproduce the failure with master.

**Comment by lamont-granquist** [comment]
More context might help, you don't post which URL failed or anything.

I can also download it using my personal non-work creds for my private s3 account just fine with s3cmd:

```
 s3cmd get s3://opscode-omnibus-cache/ruby-2.2.2-cd03b28fd0b555970f5c4fd481700852
```

this URL also works fine in a browser with no auth:

```
http://opscode-omnibus-cache.s3.amazonaws.com/ruby-2.2.2-cd03b28fd0b555970f5c4fd481700852
```

so i got no idea...

**Comment by ranjib** [comment]
sorry, @lamont-granquist i didnt notice i have skipped the initial part of the log. i have updated the description. it looks like the hash inside the url is different

**Comment by lamont-granquist** [comment]
weird, copypasta error on the md5, try it again.

**Comment by ranjib** [comment]
this was fixed after @jaym 's latest commit. I can build omnibus from master now.
For posterity, i was using omnibus cookbook to configure base system and the following build script: https://github.com/ranjib/PiChef/blob/master/site-cookbooks/raspi/files/default/build_chef.sh
